name: Deploy AeroMetrics

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Start Deployment
        run: echo "🚀 Starting deployment at %DATE% %TIME%"

      - name: Deploy App
        run: powershell -ExecutionPolicy Bypass -File "C:\Users\RAKA\Documents\Work\deploy\AeroMetrics\deploy.ps1"

      - name: End Deployment
        run: echo "Deployment completed"