name: Deploy AeroMetrics

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: cmd

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Start Deployment
        run: echo Starting deployment

      - name: Deploy App
        run: powershell -ExecutionPolicy Bypass -File "C:\deploy\AeroMetrics\deploy.ps1"

      - name: Done
        run: echo Deployment completedm Sucessfully